function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id ~= hash "fastforward" then return end

	if action.pressed then
		msg.post("loader:/game#collectionproxy", "set_time_step", {factor = 4, mode = 0})
	elseif action.released then
		msg.post("loader:/game#collectionproxy", "set_time_step", {factor = 1, mode = 0})
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
